import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = { title: 'Gizlilik', description: 'Fidan Bahçem hesap, sipariş ve ödeme verilerinin kullanımı.' };

export default function Privacy() {
  return <><SiteHeader /><main id="main-content" tabIndex={-1} className="mx-auto max-w-3xl px-5 py-12">
    <p className="eyebrow">Verileriniz sizin kontrolünüzde</p><h1 className="page-title">Gizlilik</h1>
    <p className="mt-4 text-sm text-[var(--muted)]">Güncelleme: 1 Ekim 2026</p>
    <div className="mt-8 space-y-8 leading-8">
      <section><h2 className="font-serif text-2xl">Hesap ve giriş</h2><p className="mt-3">Hesabınız için adınızı ve e-posta adresinizi saklarız. Şifre ile girişte şifrenizin kendisi yerine güvenli özeti tutulur. Google ile giriş kullanıma açıldığında yalnızca kimlik, e-posta ve profil kapsamları istenir; Google hesap kimliğiniz hesabınızla eşleştirilir. Gmail mesajlarınıza veya Google Drive dosyalarınıza erişilmez.</p><p className="mt-3">Oturumunuz yalnızca sunucunun okuyabildiği bir çerezle yönetilir. Google giriş işlemi için kısa süreli bir doğrulama çerezi kullanılır. Şifre kurtarma, size gösterilen özel kurtarma koduyla yapılır; şifre sıfırlama e-postası gönderilmez.</p></section>
      <section><h2 className="font-serif text-2xl">Sepet ve demo siparişleri</h2><p className="mt-3">Sepetiniz bu tarayıcının yerel depolamasında tutulur. Sipariş kaydı için iletişim, teslimat adresi ve seçtiğiniz ürünler saklanır. Fidan siparişleri demo olarak kaydedilir; bu işlem tahsilat veya otomatik sevkiyat başlatmaz ve kart bilgisi istenmez.</p><p className="mt-3">Kesintiye uğrayan bir siparişi aynı kayıtla yeniden deneyebilmeniz için sipariş denemesi, hesap kimliği, ürünler, iletişim bilgileri ve adres bu sekmenin oturum depolamasında tutulur. Kayıt, sipariş doğrulanınca, kesin olarak reddedilince, sekme kapatılınca veya süresi geçmiş ya da bozuk kaydı açıkça kaldırınca temizlenir.</p><p className="mt-3">Misafir siparişleri 90 gün sonra silinir. Hesabınıza bağlı siparişler siz hesabınızı silene kadar saklanır. Misafir siparişleri sonradan açılan bir hesaba otomatik olarak bağlanmaz.</p></section>
      <section><h2 className="font-serif text-2xl">Hesap ödemeleri</h2><p className="mt-3">Hesabınıza ayrıca bir ödeme paketi sunulursa ödeme ekranı RevenueCat ve ilgili ödeme sağlayıcısı tarafından yönetilir. Hesap kimliğiniz ve ödeme sırasında e-posta adresiniz sağlayıcıya iletilir. Kart bilgilerinizi mağaza sunucusunda saklamayız. Sağlayıcıdan doğrulanan satın alma, abonelik ve erişim durumları hesabınıza kaydedilir.</p><p className="mt-3">Bu ödemeler demo fidan siparişlerinden ayrıdır. Gerçek ücret, dönem ve yenileme bilgisi ilgili ödeme ekranında gösterilir. Hesap silmek sağlayıcıdaki aboneliğinizi kendiliğinden iptal etmez; etkin aboneliğinizi önce Hesabım sayfasındaki yönetim bağlantısından yönetin. Ödeme sağlayıcısının kendi saklama koşulları da geçerlidir.</p></section>
      <section><h2 className="font-serif text-2xl">Erişim ve silme</h2><p className="mt-3"><Link href="/hesabim" className="underline underline-offset-4">Hesabım</Link> sayfasından hesap verilerinizi indirebilir, bilgilerinizi güncelleyebilir veya hesabınızı ve bağlı yerel kayıtlarınızı silebilirsiniz. Şifreli hesaplarda şifre doğrulaması, Google ile açılan hesaplarda yakın zamanda Google ile yeniden doğrulama ve açık silme onayı gerekir.</p><p className="mt-3">Veriler Deno Deploy tarafından yönetilen veritabanında saklanır. Güvenlik amacıyla istek sıklığını sınırlayan kısa süreli kayıtlar ve ödeme bildirimlerinin tekrar işlenmesini önleyen teknik kayıtlar tutulur. Reklam veya analiz çerezi kullanılmaz.</p></section>
    </div>
  </main><SiteFooter /></>;
}
