'use client';
import { FormEvent, useEffect, useState } from 'react';
import { SiteHeader } from '@/components/site-header';
import { formatPrice } from '@/lib/products';
type Order = {id:string;status:string;total:number;createdAt:string;shipping:Record<string,string>;items:{name:string;quantity:number}[]};
export default function Admin(){
  const [orders,setOrders]=useState<Order[]|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch('/api/store/admin-orders');const d=await r.json();if(r.ok)setOrders(d.orders);}
  useEffect(()=>{const task=setTimeout(()=>void load().catch(()=>setMessage('Siparişler yüklenemedi. Tekrar deneyin.')),0);return ()=>clearTimeout(task);},[]);
  async function action(name:string,data:unknown){setBusy(true);setMessage('');try{const r=await fetch('/api/store/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error);if(name==='admin-logout')setOrders(null);else await load();}catch(e){setMessage(e instanceof Error?e.message:'Tekrar deneyin.');}finally{setBusy(false);}}
  function login(e:FormEvent<HTMLFormElement>){e.preventDefault();void action('admin-login',Object.fromEntries(new FormData(e.currentTarget)));}
  return <><SiteHeader/><main className="mx-auto max-w-5xl px-5 py-12"><h1 className="page-title">Sipariş yönetimi</h1>{message&&<p role="alert" className="mt-5">{message}</p>}{orders===null?<form onSubmit={login} className="checkout-panel form-grid mt-8 max-w-xl"><label className="full">Yönetici anahtarı<input type="password" name="key" required autoComplete="off"/></label><button disabled={busy} className="primary-button full">Giriş yap</button></form>:<><button onClick={()=>void action('admin-logout',{})} className="secondary-button my-6">Çıkış yap</button>{!orders.length&&<p>Henüz sipariş yok.</p>}{orders.map(order=><article key={order.id} className="checkout-panel mb-6"><p className="break-all font-semibold">{order.id}</p><p className="my-3">{order.shipping.name} · {order.shipping.email} · {order.shipping.phone}</p><p>{order.shipping.address}, {order.shipping.district} / {order.shipping.city}</p><p className="my-3">{order.items.map(item=>`${item.quantity} × ${item.name}`).join(', ')} · {formatPrice(order.total)}</p><label>Sipariş durumu <select value={order.status} disabled={busy} onChange={e=>void action('admin-status',{id:order.id,status:e.target.value})} className="ml-3 rounded-lg border p-2">{['Alındı','Hazırlanıyor','Kargoya verildi','Teslim edildi','İptal edildi'].map(status=><option key={status}>{status}</option>)}</select></label><p className="mt-3 text-sm">Demo ödeme · {new Date(order.createdAt).toLocaleString('tr-TR')}</p></article>)}</>}</main></>;
}
