import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
const origin = process.argv[2] || 'http://127.0.0.1:3000';
let session = '';
async function call(action, data, expected = 200, suppliedOrigin = origin) {
  const response = await fetch(`${origin}/api/store/${action}`, {
    method: data ? 'POST' : 'GET',
    headers: { ...(data ? { 'Content-Type':'application/json', Origin:suppliedOrigin } : {}), ...(session ? { Cookie:session } : {}) },
    ...(data ? {body:JSON.stringify(data)} : {}),
  });
  const body = await response.json();
  assert.equal(response.status, expected, `${action}: ${JSON.stringify(body)}`);
  const cookie = response.headers.get('set-cookie'); if(cookie) session = cookie.split(';')[0];
  return body;
}
for(const path of ['/','/fidanlar','/odeme','/hesabim','/gizlilik','/yonetim']) assert.equal((await fetch(origin+path)).status,200,path);
assert.equal((await fetch(origin+'/missing-page')).status,404);
const authConfiguration = await (await fetch(origin+'/api/auth/config')).json();
assert.equal(typeof authConfiguration.googleAvailable,'boolean');
if (authConfiguration.googleAvailable) {
  const started = await fetch(origin+'/api/auth/google', { redirect: 'manual' });
  assert.equal(started.status, 303);
  const authorization = new URL(started.headers.get('location'));
  assert.equal(authorization.origin, 'https://accounts.google.com');
  assert.equal(authorization.searchParams.get('redirect_uri'), origin+'/api/auth/google/callback');
  assert.equal(authorization.searchParams.get('scope'), 'openid email profile');
  assert.equal(authorization.searchParams.get('code_challenge_method'), 'S256');
  const oauthState = authorization.searchParams.get('state');
  assert.match(oauthState, /^[a-f0-9]{64}$/);
  const oauthCookie = started.headers.get('set-cookie');
  assert.match(oauthCookie, /HttpOnly/i);
  assert.match(oauthCookie, /SameSite=Lax/i);
  if (origin.startsWith('https:')) assert.match(oauthCookie, /Secure/i);
  const callback = origin+'/api/auth/google/callback?'+new URLSearchParams({ state: oauthState, error: 'access_denied' });
  const callbackOptions = { redirect: 'manual', headers: { Cookie: oauthCookie.split(';')[0] } };
  const cancelled = await fetch(callback, callbackOptions);
  assert.equal(cancelled.status, 303);
  const destination = new URL(cancelled.headers.get('location'));
  assert.equal(destination.origin, origin);
  assert.equal(destination.searchParams.get('auth_error'), 'cancelled');
  assert.match(cancelled.headers.get('set-cookie'), /Max-Age=0/i);
  const replayed = await fetch(callback, callbackOptions);
  assert.equal(new URL(replayed.headers.get('location')).searchParams.get('auth_error'), 'invalid_state');
}
assert.equal((await fetch(origin+'/api/billing/status')).status,401);
await call('health');
assert.equal((await fetch(`${origin}/api/store/register`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{invalid'})).status,400);
assert.equal((await fetch(`${origin}/api/store/register`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({oversized:'x'.repeat(17000)})})).status,413);
await call('profile',{name:'Blocked'},403,'https://attacker.example');
await call('profile',{name:'Blocked'},403,'not-an-origin');
const alternateScheme = origin.startsWith('https:') ? origin.replace('https:', 'http:') : origin.replace('http:', 'https:');
await call('profile',{name:'Blocked'},403,alternateScheme);
for (const body of ['null','[]','true','"text"']) assert.equal((await fetch(`${origin}/api/store/register`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body})).status,400);
const address = `qa-${randomUUID()}@example.com`;
const password = `Test-${randomUUID()}!`;
const registered = await call('register',{name:'Production QA',email:address,password});
assert.ok(registered.recoveryCode);
assert.equal((await call('me')).user.email,address);
assert.equal((await call('me')).user.hasPassword,true);
const billing = await fetch(origin+'/api/billing/status',{headers:{Cookie:session}});
assert.equal(billing.status,200);
assert.equal(typeof (await billing.json()).config.enabled,'boolean');
await call('login',{email:address,password:'wrong'},401);
const requestId = randomUUID();
const orderData = {requestId,demoConsent:true,items:[{id:'findik',quantity:2}],name:'QA Customer',email:address,phone:'05550000000',address:'Synthetic Test Street 1',city:'İstanbul',district:'Kadıköy',total:1,cardNumber:'4111111111111111',cvv:'123'};
await call('order',{...orderData,demoConsent:false},400);
await call('order',{...orderData,items:[{id:'findik',quantity:1},{id:'findik',quantity:1}]},400);
await call('order',{...orderData,phone:'invalid'},400);
const created = await call('order',orderData,201);
assert.equal(created.order.total,459);
assert.equal((await call('order',orderData)).order.id,created.order.id);
await call('order',{...orderData,address:'Changed request'},409);
assert.equal((await call('orders')).orders.length,1);
await call('order',{...orderData,requestId:randomUUID(),items:[{id:'findik',quantity:-1}]},400);
const exported = await call('export');
assert.equal(exported.user.password,undefined);
assert.ok('billing' in exported);
assert.equal(exported.orders[0].payment,'demo-completed');
assert.equal(JSON.stringify(exported).includes('cardNumber'),false);
await call('admin-orders',undefined,401);
const customerSession = session;
const adminKey = process.env.ADMIN_TEST_KEY || (process.argv[3] ? readFileSync(process.argv[3],'utf8').match(/Administrator key: (.+)/)?.[1] : undefined);
if(adminKey) {
  await call('admin-login',{key:'incorrect-key'},401);
  await call('admin-login',{key:adminKey});
  assert.ok((await call('admin-orders')).orders.some(order=>order.id===created.order.id));
  await call('admin-status',{id:created.order.id,status:'Hazırlanıyor'});
  await call('admin-status',{id:created.order.id,status:'invalid'},400);
  await call('admin-logout',{});
  session=customerSession;
  assert.equal((await call('orders')).orders[0].status,'Hazırlanıyor');
}
await call('logout',{});
assert.equal((await call('me')).user,null);
await call('orders',undefined,401);
const other = await call('register',{name:'Isolation QA',email:`qa-${randomUUID()}@example.com`,password});
assert.ok(other.user);
assert.equal((await call('orders')).orders.length,0);
await call('delete',{password});
await call('login',{email:address,password});
assert.equal((await call('orders')).orders[0].id,created.order.id);
await call('profile',{name:'Updated QA'});
assert.equal((await call('me')).user.name,'Updated QA');
await call('password',{currentPassword:'incorrect',password:`Changed-${randomUUID()}`},401);
const newPassword=`Recovered-${randomUUID()}`;
await call('recover',{email:address,recoveryCode:'incorrect',password:newPassword},401);
const recovery=await call('recover',{email:address,recoveryCode:registered.recoveryCode,password:newPassword});
assert.ok(recovery.recoveryCode);
assert.equal((await call('me')).user,null);
await call('login',{email:address,password},401);
await call('login',{email:address,password:newPassword});
await call('delete',{password:'incorrect'},401);
await call('delete',{password:newPassword});
assert.equal((await call('me')).user,null);
await call('login',{email:address,password},401);
console.log('PASS: pages/404, health, auth/billing configuration'+(authConfiguration.googleAvailable?', live OAuth start/cancellation/replay':'')+', CSRF/scheme/malformed origins, JSON validation, registration, sessions, login failure, demo consent, duplicate items/phone checks, durable orders, immutable idempotency, price integrity, privacy export, isolation, recovery and session revocation, profile, account deletion'+(adminKey?', admin authorization and order management':''));
